<template>
  <div class="md:grid grid-cols-3 gap-4">
    <!-- Left Section: Email Groups -->
    <div>
      <h2 class="text-lg tracking-tight uppercase font-semibold text-gray-800 dark:text-gray-100 mb-2">Email groups:</h2>
      
      <!-- Autogenerated Lists -->
      <div class="mb-4 space-y-2">
        <button @click="viewEmailList('__students__')" class="w-full text-left px-3 py-2 border border-gray-200 dark:border-gray-700 rounded-lg hover:bg-gray-50 dark:hover:bg-gray-800 transition">
          <span class="flex items-center justify-between">
            <span class="text-gray-800 dark:text-gray-100 inline-flex gap-2 items-center">
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-4 h-4">
                <path fill-rule="evenodd" d="M9.664 1.319a.75.75 0 0 1 .672 0 41.059 41.059 0 0 1 8.198 5.424.75.75 0 0 1-.254 1.285 31.372 31.372 0 0 0-7.86 3.83.75.75 0 0 1-.84 0 31.508 31.508 0 0 0-2.08-1.287V9.394c0-.244.116-.463.302-.592a35.504 35.504 0 0 1 3.305-2.033.75.75 0 0 0-.714-1.319 37 37 0 0 0-3.446 2.12A2.216 2.216 0 0 0 6 9.393v.38a31.293 31.293 0 0 0-4.28-1.746.75.75 0 0 1-.254-1.285 41.059 41.059 0 0 1 8.198-5.424ZM6 11.459a29.848 29.848 0 0 0-2.455-1.158 41.029 41.029 0 0 0-.39 3.114.75.75 0 0 0 .419.74c.528.256 1.046.53 1.554.82-.21.324-.455.63-.739.914a.75.75 0 1 0 1.06 1.06c.37-.369.69-.77.96-1.193a26.61 26.61 0 0 1 3.095 2.348.75.75 0 0 0 .992 0 26.547 26.547 0 0 1 5.93-3.95.75.75 0 0 0 .42-.739 41.053 41.053 0 0 0-.39-3.114 29.925 29.925 0 0 0-5.199 2.801 2.25 2.25 0 0 1-2.514 0c-.41-.275-.826-.541-1.25-.797a6.985 6.985 0 0 1-1.084 3.45 26.503 26.503 0 0 0-1.281-.78A5.487 5.487 0 0 0 6 12v-.54Z" clip-rule="evenodd" />
              </svg>
              Student Emails
            </span>
            <span class="inline-flex items-center justify-center w-6 h-6 text-xs font-semibold text-white bg-orange-600 rounded-full">
              {{ clubPrivate?.members?.length || 0 }}
            </span>
          </span>
        </button>
        
        <button v-if="canViewMembers" @click="viewEmailList('__personal__')" class="w-full text-left px-3 py-2 border border-gray-200 dark:border-gray-700 rounded-lg hover:bg-gray-50 dark:hover:bg-gray-800 transition">
          <span class="flex items-center justify-between">
            <span class="text-gray-800 dark:text-gray-100 inline-flex gap-2 items-center">
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-4 h-4">
                <path fill-rule="evenodd" d="M9.293 2.293a1 1 0 0 1 1.414 0l7 7A1 1 0 0 1 17 11h-1v6a1 1 0 0 1-1 1h-2a1 1 0 0 1-1-1v-3a1 1 0 0 0-1-1H9a1 1 0 0 0-1 1v3a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1v-6H3a1 1 0 0 1-.707-1.707l7-7Z" clip-rule="evenodd" />
              </svg>
              Personal Emails
            </span>
            <span class="inline-flex items-center justify-center w-6 h-6 text-xs font-semibold text-white bg-orange-600 rounded-full">
              {{ personalEmails.length }}
            </span>
          </span>
        </button>
      </div>

      <!-- Custom Lists -->
      <div class="space-y-2">
        <div v-for="list in emailLists" :key="list.id" class="border border-gray-200 dark:border-gray-700 rounded-lg">
          <div class="flex items-center justify-between px-3 py-2">
            <button @click="viewEmailList(list.id)" class="flex-1 text-left flex items-center justify-between hover:opacity-80">
              <span class="text-gray-800 dark:text-gray-100 inline-flex items-center gap-2">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-4 h-4">
                  <path fill-rule="evenodd" d="M5.404 14.596A6.5 6.5 0 1 1 16.5 10a1.25 1.25 0 0 1-2.5 0 4 4 0 1 0-.571 2.06A2.75 2.75 0 0 0 18 10a8 8 0 1 0-2.343 5.657.75.75 0 0 0-1.06-1.06 6.5 6.5 0 0 1-9.193 0ZM10 7.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5Z" clip-rule="evenodd" />
                </svg>
                {{ list.name }}
              </span>
              <div class="flex items-center gap-1">
                <template v-if="canModifyEmails">
                  <button @click.stop="startEditingList(list)" class="text-blue-600 hover:text-blue-700 dark:text-blue-400 dark:hover:text-blue-300 p-1 rounded hover:bg-blue-50 dark:hover:bg-blue-900/20">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor" class="w-4 h-4">
                      <path d="M13.488 2.513a1.75 1.75 0 0 0-2.475 0L6.75 6.774a2.75 2.75 0 0 0-.596.892l-.848 2.047a.75.75 0 0 0 .98.98l2.047-.848a2.75 2.75 0 0 0 .892-.596l4.261-4.262a1.75 1.75 0 0 0 0-2.474Z" />
                      <path d="M4.75 3.5c-.69 0-1.25.56-1.25 1.25v6.5c0 .69.56 1.25 1.25 1.25h6.5c.69 0 1.25-.56 1.25-1.25V9A.75.75 0 0 1 14 9v2.25A2.75 2.75 0 0 1 11.25 14h-6.5A2.75 2.75 0 0 1 2 11.25v-6.5A2.75 2.75 0 0 1 4.75 2H7a.75.75 0 0 1 0 1.5H4.75Z" />
                    </svg>
                  </button>
                  <button @click.stop="confirmDeleteList(list)" class="text-red-600 hover:text-red-700 dark:text-red-400 dark:hover:text-red-300 p-1 rounded hover:bg-red-50 dark:hover:bg-red-900/20">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor" class="w-4 h-4">
                      <path fill-rule="evenodd" d="M5 3.25V4H2.75a.75.75 0 0 0 0 1.5h.3l.815 8.15A1.5 1.5 0 0 0 5.357 15h5.285a1.5 1.5 0 0 0 1.493-1.35l.815-8.15h.3a.75.75 0 0 0 0-1.5H11v-.75A2.25 2.25 0 0 0 8.75 1h-1.5A2.25 2.25 0 0 0 5 3.25Zm2.25-.75a.75.75 0 0 0-.75.75V4h3v-.75a.75.75 0 0 0-.75-.75h-1.5ZM6.05 6a.75.75 0 0 1 .787.713l.275 5.5a.75.75 0 0 1-1.498.075l-.275-5.5A.75.75 0 0 1 6.05 6Zm3.9 0a.75.75 0 0 1 .712.787l-.275 5.5a.75.75 0 0 1-1.498-.075l.275-5.5a.75.75 0 0 1 .786-.711Z" clip-rule="evenodd" />
                    </svg>
                  </button>
                </template>
                <span class="inline-flex items-center justify-center w-6 h-6 text-xs font-semibold text-white bg-orange-600 rounded-full">
                  {{ list.emails.length }}
                </span>
              </div>
            </button>
          </div>
        </div>
        
        <button v-if="canModifyEmails" @click="startCreatingList" class="w-full text-sm text-orange-600 hover:text-orange-700 dark:text-orange-400 dark:hover:text-orange-300 text-left px-3 py-2">
          + Add custom email list
        </button>
      </div>
    </div>

    <!-- Middle Section: Automatic Reminders -->
    <div>
      <h2 class="text-lg tracking-tight uppercase font-semibold text-gray-800 dark:text-gray-100 mb-2">Automatic reminders:</h2>
      
      <!-- Google Auth Required Check -->
      <div v-if="!googleAccountStore.email" class="mb-3 p-3 bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-lg">
        <p class="text-sm text-blue-800 dark:text-blue-200 mb-2">
          ⚠️ Google account connection required to send automatic reminders
        </p>
        <button @click="showGoogleAuthDialog = true" class="text-sm px-3 py-1 bg-blue-600 hover:bg-blue-700 text-white rounded">
          Connect Google Account
        </button>
      </div>

      <!-- Reminder Configuration -->
      <div v-if="canModifyEmails" class="space-y-3">
        <label class="flex items-center space-x-2">
          <input type="checkbox" v-model="reminderSettings.enabled" :disabled="!googleAccountStore.email" class="w-4 h-4 text-orange-600 bg-gray-100 border-gray-300 rounded focus:ring-orange-500 dark:focus:ring-orange-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600 disabled:opacity-50">
          <span class="text-gray-800 dark:text-gray-200 font-medium">Enable automatic reminders</span>
        </label>

        <div v-if="reminderSettings.enabled" class="pl-6 space-y-3">
          <p class="text-xs text-gray-600 dark:text-gray-400">Reminders will be sent 1 day before each meeting</p>
          
          <!-- Select Email Lists -->
          <div>
            <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">Send to:</label>
            <div class="space-y-2">
              <label class="flex items-center space-x-2">
                <input type="checkbox" :checked="reminderSettings.listIds.includes('__students__')" @change="toggleReminderList('__students__')" class="w-4 h-4 text-orange-600 bg-gray-100 border-gray-300 rounded focus:ring-orange-500">
                <span class="text-sm text-gray-800 dark:text-gray-200">Student Emails</span>
              </label>
              <label v-if="canViewMembers" class="flex items-center space-x-2">
                <input type="checkbox" :checked="reminderSettings.listIds.includes('__personal__')" @change="toggleReminderList('__personal__')" class="w-4 h-4 text-orange-600 bg-gray-100 border-gray-300 rounded focus:ring-orange-500">
                <span class="text-sm text-gray-800 dark:text-gray-200">Personal Emails</span>
              </label>
              <label v-for="list in emailLists" :key="list.id" class="flex items-center space-x-2">
                <input type="checkbox" :checked="reminderSettings.listIds.includes(list.id)" @change="toggleReminderList(list.id)" class="w-4 h-4 text-orange-600 bg-gray-100 border-gray-300 rounded focus:ring-orange-500">
                <span class="text-sm text-gray-800 dark:text-gray-200">{{ list.name }}</span>
              </label>
            </div>
          </div>

          <!-- Email Template -->
          <div>
            <FormInput v-model="reminderSettings.subject" label="Email Subject" type="text" required placeholder="Meeting Reminder" class="mb-2" />
            <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Email Body</label>
            <textarea v-model="reminderSettings.body" required rows="4" 
              class="bg-gray-50 border border-gray-200 text-gray-900 text-sm rounded-md focus:ring-orange-400 focus:border-orange-400 block w-full px-2 py-1 dark:bg-gray-800 dark:border-gray-700 dark:placeholder-gray-400 dark:text-white"
              placeholder="Don't forget about our meeting tomorrow!"></textarea>
          </div>

          <!-- Save Button -->
          <button @click="saveReminderSettings" class="w-full px-4 py-2 bg-orange-600 hover:bg-orange-700 text-white text-sm font-medium rounded-lg">
            Save Reminder Settings
          </button>
        </div>
      </div>

      <p v-else-if="!canModifyEmails" class="text-sm text-gray-600 dark:text-gray-400 italic">
        You don't have permission to configure reminders
      </p>
    </div>

    <!-- Right Section: Other Tools -->
    <div>
      <h2 class="text-lg tracking-tight uppercase font-semibold text-gray-800 dark:text-gray-100 mb-2">Other tools:</h2>
      <button
        class="text-white bg-orange-600 hover:bg-orange-700 focus:ring-4 focus:outline-hidden focus:ring-orange-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-orange-600 dark:hover:bg-orange-700 dark:focus:ring-orange-800 block mb-2"
        
      >
        Send custom email
      </button>
    </div>
  </div>

  <!-- Email List Modal (for viewing/editing) -->
  <EmailListModal
    v-model:show="showEmailModal"
    v-model:emails="modalEmails"
    v-model:name="modalName"
    :title="modalTitle"
    :editable="modalEditable"
    @save="handleSaveModal"
  />

  <!-- Google Authorization Dialog -->
  <GoogleAuthorizationDialog
    :open="showGoogleAuthDialog"
    :requested-scopes="scopes"
    :club-id="club.id"
  />
</template>

<script setup lang="ts">
import { db } from '@/firebase';
import { type ClubPrivate, OfficerPermission, type Club, type ClubEmailList, type ClubRole, type ClubEmailReminders } from '@/schema';
import { typedGetDoc, typedGetDocs, type DocWithId } from '@/utils';
import { collection, type DocumentReference, addDoc, doc, updateDoc, deleteDoc } from 'firebase/firestore';
import { computed, ref, getCurrentInstance } from 'vue';
import EmailListModal from '@/components/ui/EmailListModal.vue';
import FormInput from '@/components/form/FormInput.vue';
import GoogleAuthorizationDialog from '@/components/auth/GoogleAuthorizationDialog.vue';
import { useGoogleAccountStore } from '@/stores/googleAccount';
import api from '@/api';
import { showSuccessToast, showErrorToast, showConfirmDialog, showWarningToast } from '@/toast';

const props = defineProps<{
  role: ClubRole,
  school: string,
  club: DocWithId<Club>,
  clubDoc: DocumentReference,
  clubPrivateDoc: DocumentReference
}>();

const appContext = getCurrentInstance()?.appContext;

const canModifyEmails = computed(() => props.role.stuco || (props.role.officer & OfficerPermission.Messages));
const canViewMembers = computed(() => props.role.stuco || (props.role.officer & OfficerPermission.Members));

// Google account store
const scopes = ["openid", "https://www.googleapis.com/auth/userinfo.email", "https://www.googleapis.com/auth/gmail.send"];
const googleAccountStore = useGoogleAccountStore(props.club.id);
const showGoogleAuthDialog = ref(false);

const emailListsCollection = collection(props.clubDoc, "emails");
const emailLists = ref<DocWithId<ClubEmailList>[]>(await typedGetDocs(emailListsCollection));
const clubPrivate = ref(await typedGetDoc<ClubPrivate>(props.clubPrivateDoc));

// Fetch personal emails
const personalEmails = ref<string[]>([]);
if (canViewMembers.value) {
  try {
    const result = await api.club.personalEmails.query({ clubId: props.club.id });
    personalEmails.value = result.emails;
  } catch (error) {
    console.error('Failed to fetch personal emails:', error);
  }
}

// Modal state
const showEmailModal = ref(false);
const modalTitle = ref("");
const modalEmails = ref<string[]>([]);
const modalName = ref("");
const modalEditable = ref(false);
const modalMode = ref<'view' | 'create' | 'edit'>('view');
const editingListId = ref<string | null>(null);

// Mailto generator state
const showMailtoModal = ref(false);
const selectedMailtoLists = ref<Set<string>>(new Set());

// Reminder settings state - computed from clubPrivate
const reminderSettings = computed<ClubEmailReminders>({
  get: () => ({
    enabled: clubPrivate.value?.email_reminders?.enabled || false,
    subject: clubPrivate.value?.email_reminders?.subject || '',
    body: clubPrivate.value?.email_reminders?.body || '',
    listIds: clubPrivate.value?.email_reminders?.listIds || []
  }),
  set: (value) => {
    if (clubPrivate.value) {
      clubPrivate.value.email_reminders = value;
    }
  }
});

// Helper function to get email list by ID
function getEmailList(listId: string): { name: string, emails: string[] } | null {
  if (listId === '__students__') {
    return { name: 'Student Emails', emails: clubPrivate.value?.members || [] };
  } else if (listId === '__personal__') {
    return { name: 'Personal Emails', emails: personalEmails.value };
  } else {
    const list = emailLists.value.find(l => l.id === listId);
    return list ? { name: list.name, emails: list.emails } : null;
  }
}

function viewEmailList(listId: string) {
  const list = getEmailList(listId);
  if (!list) return;
  
  modalTitle.value = list.name;
  modalEmails.value = [...list.emails];
  modalName.value = list.name;
  modalEditable.value = false;
  modalMode.value = 'view';
  showEmailModal.value = true;
}

function startCreatingList() {
  modalTitle.value = "Create Email List";
  modalEmails.value = [''];
  modalName.value = "";
  modalEditable.value = true;
  modalMode.value = 'create';
  editingListId.value = null;
  showEmailModal.value = true;
}

function startEditingList(list: DocWithId<ClubEmailList>) {
  modalTitle.value = "Edit Email List";
  modalEmails.value = [...list.emails];
  modalName.value = list.name;
  modalEditable.value = true;
  modalMode.value = 'edit';
  editingListId.value = list.id;
  showEmailModal.value = true;
}

async function handleSaveModal(data: { name: string, emails: string[] }) {
  try {
    const cleanEmails = data.emails.filter(e => e.trim() !== '');
    
    if (modalMode.value === 'create') {
      const newList: ClubEmailList = {
        name: data.name,
        emails: cleanEmails
      };
      const docRef = await addDoc(emailListsCollection, newList);
      emailLists.value.push({ id: docRef.id, ...newList });
      showSuccessToast('Email list created successfully', appContext, 3000);
    } else if (modalMode.value === 'edit' && editingListId.value) {
      const listRef = doc(emailListsCollection, editingListId.value);
      await updateDoc(listRef, {
        name: data.name,
        emails: cleanEmails
      });
      
      const list = emailLists.value.find(l => l.id === editingListId.value);
      if (list) {
        list.emails = cleanEmails;
        list.name = data.name;
      }
      showSuccessToast('Email list updated successfully', appContext, 3000);
    }
  } catch (error) {
    console.error('Failed to save email list:', error);
    showErrorToast('Failed to save email list', appContext, 3000);
  }
}

async function confirmDeleteList(list: DocWithId<ClubEmailList>) {
  const confirmed = await showConfirmDialog({
    title: 'Delete Email List',
    message: `Are you sure you want to delete '${list.name}'? This action cannot be undone.`,
    confirmText: 'Delete'
  }, appContext);
  
  if (confirmed) {
    try {
      const listRef = doc(emailListsCollection, list.id);
      await deleteDoc(listRef);
      emailLists.value = emailLists.value.filter(l => l.id !== list.id);
      showSuccessToast('Email list deleted successfully', appContext, 3000);
    } catch (error) {
      console.error('Failed to delete email list:', error);
      showErrorToast('Failed to delete email list', appContext, 3000);
    }
  }
}

function toggleMailtoList(listId: string) {
  if (selectedMailtoLists.value.has(listId)) {
    selectedMailtoLists.value.delete(listId);
  } else {
    selectedMailtoLists.value.add(listId);
  }
}

function generateMailto() {
  const allEmails = new Set<string>();
  
  // Add student emails
  if (selectedMailtoLists.value.has('__students__') && clubPrivate.value?.members) {
    clubPrivate.value.members.forEach(email => allEmails.add(email));
  }
  
  // Add personal emails
  if (selectedMailtoLists.value.has('__personal__')) {
    personalEmails.value.forEach(email => allEmails.add(email));
  }
  
  // Add custom lists
  emailLists.value.forEach(list => {
    if (selectedMailtoLists.value.has(list.id)) {
      list.emails.forEach(email => allEmails.add(email));
    }
  });
  
  if (allEmails.size === 0) {
    showWarningToast('Please select at least one email list', appContext, 3000);
    return;
  }
  
  // Generate mailto link with BCC
  const bcc = Array.from(allEmails).join(',');
  const mailtoLink = `mailto:?bcc=${encodeURIComponent(bcc)}`;
  
  // Open in new window/tab
  window.location.href = mailtoLink;
  showSuccessToast(`Opening email client with ${allEmails.size} recipients`, appContext, 3000);
  showMailtoModal.value = false;
  
  // Reset selections
  selectedMailtoLists.value.clear();
}

function toggleReminderList(listId: string) {
  const index = reminderSettings.value.listIds.indexOf(listId);
  if (index > -1) {
    reminderSettings.value.listIds.splice(index, 1);
  } else {
    reminderSettings.value.listIds.push(listId);
  }
}

async function saveReminderSettings() {
  if (!googleAccountStore.email) {
    showErrorToast('Please connect a Google account first', appContext, 3000);
    return;
  }

  if (reminderSettings.value.enabled && reminderSettings.value.listIds.length === 0) {
    showWarningToast('Please select at least one email list', appContext, 3000);
    return;
  }

  if (reminderSettings.value.enabled && (!reminderSettings.value.subject || !reminderSettings.value.body)) {
    showWarningToast('Please provide both subject and body', appContext, 3000);
    return;
  }

  try {
    await updateDoc(props.clubPrivateDoc, {
      email_reminders: reminderSettings.value
    });
    showSuccessToast('Reminder settings saved successfully', appContext, 3000);
  } catch (error) {
    console.error('Failed to save reminder settings:', error);
    showErrorToast('Failed to save reminder settings', appContext, 3000);
  }
}
</script>
